# Generated by Django 5.1 on 2024-08-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_book_language_book_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstances',
            new_name='BookInstance',
        ),
    ]
